/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package AddAmbulanceDb.model.impl;

import AddAmbulanceDb.model.Ambulance;

import AddAmbulanceDb.service.AmbulanceLocalServiceUtil;

/**
 * The extended model base implementation for the Ambulance service. Represents a row in the &quot;HSP_Ambulance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AmbulanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmbulanceImpl
 * @see Ambulance
 * @generated
 */
public abstract class AmbulanceBaseImpl
	extends AmbulanceModelImpl implements Ambulance {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ambulance model instance should use the <code>Ambulance</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AmbulanceLocalServiceUtil.addAmbulance(this);
		}
		else {
			AmbulanceLocalServiceUtil.updateAmbulance(this);
		}
	}

}