/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package AddAmbulanceDb.model.impl;

import AddAmbulanceDb.model.Hospital;

import AddAmbulanceDb.service.HospitalLocalServiceUtil;

/**
 * The extended model base implementation for the Hospital service. Represents a row in the &quot;HSP_Hospital&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HospitalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HospitalImpl
 * @see Hospital
 * @generated
 */
public abstract class HospitalBaseImpl
	extends HospitalModelImpl implements Hospital {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hospital model instance should use the <code>Hospital</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			HospitalLocalServiceUtil.addHospital(this);
		}
		else {
			HospitalLocalServiceUtil.updateHospital(this);
		}
	}

}