/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.bank.model.impl;

import com.ats.bank.model.bank;
import com.ats.bank.service.bankLocalServiceUtil;

/**
 * The extended model base implementation for the bank service. Represents a row in the &quot;practice_bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link bankImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bankImpl
 * @see bank
 * @generated
 */
public abstract class bankBaseImpl extends bankModelImpl implements bank {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bank model instance should use the <code>bank</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			bankLocalServiceUtil.addbank(this);
		}
		else {
			bankLocalServiceUtil.updatebank(this);
		}
	}

}