/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.model.impl;

import com.liferay.model.customer_table;
import com.liferay.service.customer_tableLocalServiceUtil;

/**
 * The extended model base implementation for the customer_table service. Represents a row in the &quot;FOO_customer_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link customer_tableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see customer_tableImpl
 * @see customer_table
 * @generated
 */
public abstract class customer_tableBaseImpl
	extends customer_tableModelImpl implements customer_table {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer_table model instance should use the <code>customer_table</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			customer_tableLocalServiceUtil.addcustomer_table(this);
		}
		else {
			customer_tableLocalServiceUtil.updatecustomer_table(this);
		}
	}

}