/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.model.customer_table;
import com.liferay.model.customer_tableModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the customer_table service. Represents a row in the &quot;FOO_customer_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>customer_tableModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link customer_tableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see customer_tableImpl
 * @generated
 */
@JSON(strict = true)
public class customer_tableModelImpl
	extends BaseModelImpl<customer_table> implements customer_tableModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a customer_table model instance should use the <code>customer_table</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_customer_table";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"custId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"custName", Types.VARCHAR}, {"age", Types.VARCHAR},
		{"salary", Types.BIGINT}, {"gender", Types.VARCHAR},
		{"address", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("custId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("custName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("age", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salary", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("gender", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_customer_table (uuid_ VARCHAR(75) null,custId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,custName VARCHAR(75) null,age VARCHAR(75) null,salary LONG,gender VARCHAR(75) null,address VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FOO_customer_table";

	public static final String ORDER_BY_JPQL =
		" ORDER BY customer_table.custName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_customer_table.custName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CUSTNAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public customer_tableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _custId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCustId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _custId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return customer_table.class;
	}

	@Override
	public String getModelClassName() {
		return customer_table.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<customer_table, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<customer_table, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<customer_table, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((customer_table)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<customer_table, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<customer_table, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(customer_table)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<customer_table, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<customer_table, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<customer_table, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<customer_table, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<customer_table, Object>>();

			attributeGetterFunctions.put("uuid", customer_table::getUuid);
			attributeGetterFunctions.put("custId", customer_table::getCustId);
			attributeGetterFunctions.put("groupId", customer_table::getGroupId);
			attributeGetterFunctions.put(
				"companyId", customer_table::getCompanyId);
			attributeGetterFunctions.put("userId", customer_table::getUserId);
			attributeGetterFunctions.put(
				"userName", customer_table::getUserName);
			attributeGetterFunctions.put(
				"createDate", customer_table::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", customer_table::getModifiedDate);
			attributeGetterFunctions.put(
				"custName", customer_table::getCustName);
			attributeGetterFunctions.put("age", customer_table::getAge);
			attributeGetterFunctions.put("salary", customer_table::getSalary);
			attributeGetterFunctions.put("gender", customer_table::getGender);
			attributeGetterFunctions.put("address", customer_table::getAddress);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<customer_table, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<customer_table, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<customer_table, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<customer_table, String>)customer_table::setUuid);
			attributeSetterBiConsumers.put(
				"custId",
				(BiConsumer<customer_table, Long>)customer_table::setCustId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<customer_table, Long>)customer_table::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<customer_table, Long>)customer_table::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<customer_table, Long>)customer_table::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<customer_table, String>)
					customer_table::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<customer_table, Date>)
					customer_table::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<customer_table, Date>)
					customer_table::setModifiedDate);
			attributeSetterBiConsumers.put(
				"custName",
				(BiConsumer<customer_table, String>)
					customer_table::setCustName);
			attributeSetterBiConsumers.put(
				"age",
				(BiConsumer<customer_table, String>)customer_table::setAge);
			attributeSetterBiConsumers.put(
				"salary",
				(BiConsumer<customer_table, Long>)customer_table::setSalary);
			attributeSetterBiConsumers.put(
				"gender",
				(BiConsumer<customer_table, String>)customer_table::setGender);
			attributeSetterBiConsumers.put(
				"address",
				(BiConsumer<customer_table, String>)customer_table::setAddress);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCustId() {
		return _custId;
	}

	@Override
	public void setCustId(long custId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_custId = custId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getCustName() {
		if (_custName == null) {
			return "";
		}
		else {
			return _custName;
		}
	}

	@Override
	public void setCustName(String custName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_custName = custName;
	}

	@JSON
	@Override
	public String getAge() {
		if (_age == null) {
			return "";
		}
		else {
			return _age;
		}
	}

	@Override
	public void setAge(String age) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_age = age;
	}

	@JSON
	@Override
	public long getSalary() {
		return _salary;
	}

	@Override
	public void setSalary(long salary) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_salary = salary;
	}

	@JSON
	@Override
	public String getGender() {
		if (_gender == null) {
			return "";
		}
		else {
			return _gender;
		}
	}

	@Override
	public void setGender(String gender) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gender = gender;
	}

	@JSON
	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(customer_table.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), customer_table.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public customer_table toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, customer_table>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		customer_tableImpl customer_tableImpl = new customer_tableImpl();

		customer_tableImpl.setUuid(getUuid());
		customer_tableImpl.setCustId(getCustId());
		customer_tableImpl.setGroupId(getGroupId());
		customer_tableImpl.setCompanyId(getCompanyId());
		customer_tableImpl.setUserId(getUserId());
		customer_tableImpl.setUserName(getUserName());
		customer_tableImpl.setCreateDate(getCreateDate());
		customer_tableImpl.setModifiedDate(getModifiedDate());
		customer_tableImpl.setCustName(getCustName());
		customer_tableImpl.setAge(getAge());
		customer_tableImpl.setSalary(getSalary());
		customer_tableImpl.setGender(getGender());
		customer_tableImpl.setAddress(getAddress());

		customer_tableImpl.resetOriginalValues();

		return customer_tableImpl;
	}

	@Override
	public customer_table cloneWithOriginalValues() {
		customer_tableImpl customer_tableImpl = new customer_tableImpl();

		customer_tableImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		customer_tableImpl.setCustId(
			this.<Long>getColumnOriginalValue("custId"));
		customer_tableImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		customer_tableImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		customer_tableImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		customer_tableImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		customer_tableImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		customer_tableImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		customer_tableImpl.setCustName(
			this.<String>getColumnOriginalValue("custName"));
		customer_tableImpl.setAge(this.<String>getColumnOriginalValue("age"));
		customer_tableImpl.setSalary(
			this.<Long>getColumnOriginalValue("salary"));
		customer_tableImpl.setGender(
			this.<String>getColumnOriginalValue("gender"));
		customer_tableImpl.setAddress(
			this.<String>getColumnOriginalValue("address"));

		return customer_tableImpl;
	}

	@Override
	public int compareTo(customer_table customer_table) {
		int value = 0;

		value = getCustName().compareTo(customer_table.getCustName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof customer_table)) {
			return false;
		}

		customer_table customer_table = (customer_table)object;

		long primaryKey = customer_table.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<customer_table> toCacheModel() {
		customer_tableCacheModel customer_tableCacheModel =
			new customer_tableCacheModel();

		customer_tableCacheModel.uuid = getUuid();

		String uuid = customer_tableCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			customer_tableCacheModel.uuid = null;
		}

		customer_tableCacheModel.custId = getCustId();

		customer_tableCacheModel.groupId = getGroupId();

		customer_tableCacheModel.companyId = getCompanyId();

		customer_tableCacheModel.userId = getUserId();

		customer_tableCacheModel.userName = getUserName();

		String userName = customer_tableCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			customer_tableCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			customer_tableCacheModel.createDate = createDate.getTime();
		}
		else {
			customer_tableCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			customer_tableCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			customer_tableCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		customer_tableCacheModel.custName = getCustName();

		String custName = customer_tableCacheModel.custName;

		if ((custName != null) && (custName.length() == 0)) {
			customer_tableCacheModel.custName = null;
		}

		customer_tableCacheModel.age = getAge();

		String age = customer_tableCacheModel.age;

		if ((age != null) && (age.length() == 0)) {
			customer_tableCacheModel.age = null;
		}

		customer_tableCacheModel.salary = getSalary();

		customer_tableCacheModel.gender = getGender();

		String gender = customer_tableCacheModel.gender;

		if ((gender != null) && (gender.length() == 0)) {
			customer_tableCacheModel.gender = null;
		}

		customer_tableCacheModel.address = getAddress();

		String address = customer_tableCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			customer_tableCacheModel.address = null;
		}

		return customer_tableCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<customer_table, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<customer_table, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<customer_table, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((customer_table)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, customer_table>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					customer_table.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _custId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _custName;
	private String _age;
	private long _salary;
	private String _gender;
	private String _address;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<customer_table, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((customer_table)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("custId", _custId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("custName", _custName);
		_columnOriginalValues.put("age", _age);
		_columnOriginalValues.put("salary", _salary);
		_columnOriginalValues.put("gender", _gender);
		_columnOriginalValues.put("address", _address);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("custId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("custName", 256L);

		columnBitmasks.put("age", 512L);

		columnBitmasks.put("salary", 1024L);

		columnBitmasks.put("gender", 2048L);

		columnBitmasks.put("address", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private customer_table _escapedModel;

}