/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package AccountMgmtSystemDB.model.impl;

import AccountMgmtSystemDB.model.AccountMngt;

import AccountMgmtSystemDB.service.AccountMngtLocalServiceUtil;

/**
 * The extended model base implementation for the AccountMngt service. Represents a row in the &quot;Account_AccountMngt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountMngtImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountMngtImpl
 * @see AccountMngt
 * @generated
 */
public abstract class AccountMngtBaseImpl
	extends AccountMngtModelImpl implements AccountMngt {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a account mngt model instance should use the <code>AccountMngt</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AccountMngtLocalServiceUtil.addAccountMngt(this);
		}
		else {
			AccountMngtLocalServiceUtil.updateAccountMngt(this);
		}
	}

}