/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the customer_table service. Represents a row in the &quot;FOO_customer_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.model.impl.customer_tableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.model.impl.customer_tableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see customer_table
 * @generated
 */
@ProviderType
public interface customer_tableModel
	extends BaseModel<customer_table>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer_table model instance should use the {@link customer_table} interface instead.
	 */

	/**
	 * Returns the primary key of this customer_table.
	 *
	 * @return the primary key of this customer_table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer_table.
	 *
	 * @param primaryKey the primary key of this customer_table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this customer_table.
	 *
	 * @return the uuid of this customer_table
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this customer_table.
	 *
	 * @param uuid the uuid of this customer_table
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the cust ID of this customer_table.
	 *
	 * @return the cust ID of this customer_table
	 */
	public long getCustId();

	/**
	 * Sets the cust ID of this customer_table.
	 *
	 * @param custId the cust ID of this customer_table
	 */
	public void setCustId(long custId);

	/**
	 * Returns the group ID of this customer_table.
	 *
	 * @return the group ID of this customer_table
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this customer_table.
	 *
	 * @param groupId the group ID of this customer_table
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this customer_table.
	 *
	 * @return the company ID of this customer_table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this customer_table.
	 *
	 * @param companyId the company ID of this customer_table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this customer_table.
	 *
	 * @return the user ID of this customer_table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this customer_table.
	 *
	 * @param userId the user ID of this customer_table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this customer_table.
	 *
	 * @return the user uuid of this customer_table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this customer_table.
	 *
	 * @param userUuid the user uuid of this customer_table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this customer_table.
	 *
	 * @return the user name of this customer_table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this customer_table.
	 *
	 * @param userName the user name of this customer_table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this customer_table.
	 *
	 * @return the create date of this customer_table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this customer_table.
	 *
	 * @param createDate the create date of this customer_table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this customer_table.
	 *
	 * @return the modified date of this customer_table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this customer_table.
	 *
	 * @param modifiedDate the modified date of this customer_table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the cust name of this customer_table.
	 *
	 * @return the cust name of this customer_table
	 */
	@AutoEscape
	public String getCustName();

	/**
	 * Sets the cust name of this customer_table.
	 *
	 * @param custName the cust name of this customer_table
	 */
	public void setCustName(String custName);

	/**
	 * Returns the age of this customer_table.
	 *
	 * @return the age of this customer_table
	 */
	@AutoEscape
	public String getAge();

	/**
	 * Sets the age of this customer_table.
	 *
	 * @param age the age of this customer_table
	 */
	public void setAge(String age);

	/**
	 * Returns the salary of this customer_table.
	 *
	 * @return the salary of this customer_table
	 */
	public long getSalary();

	/**
	 * Sets the salary of this customer_table.
	 *
	 * @param salary the salary of this customer_table
	 */
	public void setSalary(long salary);

	/**
	 * Returns the gender of this customer_table.
	 *
	 * @return the gender of this customer_table
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this customer_table.
	 *
	 * @param gender the gender of this customer_table
	 */
	public void setGender(String gender);

	/**
	 * Returns the address of this customer_table.
	 *
	 * @return the address of this customer_table
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this customer_table.
	 *
	 * @param address the address of this customer_table
	 */
	public void setAddress(String address);

	@Override
	public customer_table cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}