/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package employe.db.layer.model.impl;

import employe.db.layer.model.employee;
import employe.db.layer.service.employeeLocalServiceUtil;

/**
 * The extended model base implementation for the employee service. Represents a row in the &quot;Practice_employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link employeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see employeeImpl
 * @see employee
 * @generated
 */
public abstract class employeeBaseImpl
	extends employeeModelImpl implements employee {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee model instance should use the <code>employee</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			employeeLocalServiceUtil.addemployee(this);
		}
		else {
			employeeLocalServiceUtil.updateemployee(this);
		}
	}

}