/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package AmbulanceDb2.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AmbSignUp service. Represents a row in the &quot;AMB_AmbSignUp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>AmbulanceDb2.model.impl.AmbSignUpModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>AmbulanceDb2.model.impl.AmbSignUpImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmbSignUp
 * @generated
 */
@ProviderType
public interface AmbSignUpModel
	extends BaseModel<AmbSignUp>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amb sign up model instance should use the {@link AmbSignUp} interface instead.
	 */

	/**
	 * Returns the primary key of this amb sign up.
	 *
	 * @return the primary key of this amb sign up
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amb sign up.
	 *
	 * @param primaryKey the primary key of this amb sign up
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this amb sign up.
	 *
	 * @return the uuid of this amb sign up
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this amb sign up.
	 *
	 * @param uuid the uuid of this amb sign up
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the otp ID of this amb sign up.
	 *
	 * @return the otp ID of this amb sign up
	 */
	public long getOtpId();

	/**
	 * Sets the otp ID of this amb sign up.
	 *
	 * @param otpId the otp ID of this amb sign up
	 */
	public void setOtpId(long otpId);

	/**
	 * Returns the group ID of this amb sign up.
	 *
	 * @return the group ID of this amb sign up
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this amb sign up.
	 *
	 * @param groupId the group ID of this amb sign up
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this amb sign up.
	 *
	 * @return the company ID of this amb sign up
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this amb sign up.
	 *
	 * @param companyId the company ID of this amb sign up
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this amb sign up.
	 *
	 * @return the user ID of this amb sign up
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this amb sign up.
	 *
	 * @param userId the user ID of this amb sign up
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this amb sign up.
	 *
	 * @return the user uuid of this amb sign up
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this amb sign up.
	 *
	 * @param userUuid the user uuid of this amb sign up
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this amb sign up.
	 *
	 * @return the user name of this amb sign up
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this amb sign up.
	 *
	 * @param userName the user name of this amb sign up
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this amb sign up.
	 *
	 * @return the create date of this amb sign up
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this amb sign up.
	 *
	 * @param createDate the create date of this amb sign up
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this amb sign up.
	 *
	 * @return the modified date of this amb sign up
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this amb sign up.
	 *
	 * @param modifiedDate the modified date of this amb sign up
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email of this amb sign up.
	 *
	 * @return the email of this amb sign up
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this amb sign up.
	 *
	 * @param email the email of this amb sign up
	 */
	public void setEmail(String email);

	/**
	 * Returns the otp of this amb sign up.
	 *
	 * @return the otp of this amb sign up
	 */
	@AutoEscape
	public String getOTP();

	/**
	 * Sets the otp of this amb sign up.
	 *
	 * @param OTP the otp of this amb sign up
	 */
	public void setOTP(String OTP);

	/**
	 * Returns the status of this amb sign up.
	 *
	 * @return the status of this amb sign up
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this amb sign up is status.
	 *
	 * @return <code>true</code> if this amb sign up is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this amb sign up is status.
	 *
	 * @param status the status of this amb sign up
	 */
	public void setStatus(boolean status);

	@Override
	public AmbSignUp cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}