/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package checkIndb3.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the check service. Represents a row in the &quot;practice_check&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>checkIndb3.model.impl.checkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>checkIndb3.model.impl.checkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see check
 * @generated
 */
@ProviderType
public interface checkModel
	extends BaseModel<check>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a check model instance should use the {@link check} interface instead.
	 */

	/**
	 * Returns the primary key of this check.
	 *
	 * @return the primary key of this check
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this check.
	 *
	 * @param primaryKey the primary key of this check
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this check.
	 *
	 * @return the uuid of this check
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this check.
	 *
	 * @param uuid the uuid of this check
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the check in ID of this check.
	 *
	 * @return the check in ID of this check
	 */
	public long getCheckInId();

	/**
	 * Sets the check in ID of this check.
	 *
	 * @param checkInId the check in ID of this check
	 */
	public void setCheckInId(long checkInId);

	/**
	 * Returns the group ID of this check.
	 *
	 * @return the group ID of this check
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this check.
	 *
	 * @param groupId the group ID of this check
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this check.
	 *
	 * @return the company ID of this check
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this check.
	 *
	 * @param companyId the company ID of this check
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this check.
	 *
	 * @return the user ID of this check
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this check.
	 *
	 * @param userId the user ID of this check
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this check.
	 *
	 * @return the user uuid of this check
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this check.
	 *
	 * @param userUuid the user uuid of this check
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this check.
	 *
	 * @return the user name of this check
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this check.
	 *
	 * @param userName the user name of this check
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this check.
	 *
	 * @return the create date of this check
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this check.
	 *
	 * @param createDate the create date of this check
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this check.
	 *
	 * @return the modified date of this check
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this check.
	 *
	 * @param modifiedDate the modified date of this check
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the date of this check.
	 *
	 * @return the date of this check
	 */
	public Date getDate();

	/**
	 * Sets the date of this check.
	 *
	 * @param date the date of this check
	 */
	public void setDate(Date date);

	/**
	 * Returns the day of this check.
	 *
	 * @return the day of this check
	 */
	@AutoEscape
	public String getDay();

	/**
	 * Sets the day of this check.
	 *
	 * @param day the day of this check
	 */
	public void setDay(String day);

	/**
	 * Returns the check in time of this check.
	 *
	 * @return the check in time of this check
	 */
	public Date getCheckInTime();

	/**
	 * Sets the check in time of this check.
	 *
	 * @param checkInTime the check in time of this check
	 */
	public void setCheckInTime(Date checkInTime);

	/**
	 * Returns the check out time of this check.
	 *
	 * @return the check out time of this check
	 */
	public Date getCheckOutTime();

	/**
	 * Sets the check out time of this check.
	 *
	 * @param checkOutTime the check out time of this check
	 */
	public void setCheckOutTime(Date checkOutTime);

	/**
	 * Returns the total hours of this check.
	 *
	 * @return the total hours of this check
	 */
	@AutoEscape
	public String getTotalHours();

	/**
	 * Sets the total hours of this check.
	 *
	 * @param totalHours the total hours of this check
	 */
	public void setTotalHours(String totalHours);

	/**
	 * Returns the created at of this check.
	 *
	 * @return the created at of this check
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this check.
	 *
	 * @param createdAt the created at of this check
	 */
	public void setCreatedAt(Date createdAt);

	@Override
	public check cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}