/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ats.bank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the bank service. Represents a row in the &quot;practice_bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ats.bank.model.impl.bankModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ats.bank.model.impl.bankImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see bank
 * @generated
 */
@ProviderType
public interface bankModel
	extends BaseModel<bank>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bank model instance should use the {@link bank} interface instead.
	 */

	/**
	 * Returns the primary key of this bank.
	 *
	 * @return the primary key of this bank
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bank.
	 *
	 * @param primaryKey the primary key of this bank
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bank.
	 *
	 * @return the uuid of this bank
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this bank.
	 *
	 * @param uuid the uuid of this bank
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the bank ID of this bank.
	 *
	 * @return the bank ID of this bank
	 */
	public long getBankId();

	/**
	 * Sets the bank ID of this bank.
	 *
	 * @param bankId the bank ID of this bank
	 */
	public void setBankId(long bankId);

	/**
	 * Returns the group ID of this bank.
	 *
	 * @return the group ID of this bank
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bank.
	 *
	 * @param groupId the group ID of this bank
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bank.
	 *
	 * @return the company ID of this bank
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bank.
	 *
	 * @param companyId the company ID of this bank
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bank.
	 *
	 * @return the user ID of this bank
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bank.
	 *
	 * @param userId the user ID of this bank
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bank.
	 *
	 * @return the user uuid of this bank
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bank.
	 *
	 * @param userUuid the user uuid of this bank
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bank.
	 *
	 * @return the user name of this bank
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bank.
	 *
	 * @param userName the user name of this bank
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bank.
	 *
	 * @return the create date of this bank
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bank.
	 *
	 * @param createDate the create date of this bank
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bank.
	 *
	 * @return the modified date of this bank
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bank.
	 *
	 * @param modifiedDate the modified date of this bank
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this bank.
	 *
	 * @return the name of this bank
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this bank.
	 *
	 * @param name the name of this bank
	 */
	public void setName(String name);

	/**
	 * Returns the address of this bank.
	 *
	 * @return the address of this bank
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this bank.
	 *
	 * @param address the address of this bank
	 */
	public void setAddress(String address);

	@Override
	public bank cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}