/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package CaseManagementDB.model.impl;

import CaseManagementDB.model.CaseMngt;

import CaseManagementDB.service.CaseMngtLocalServiceUtil;

/**
 * The extended model base implementation for the CaseMngt service. Represents a row in the &quot;Case_CaseMngt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CaseMngtImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CaseMngtImpl
 * @see CaseMngt
 * @generated
 */
public abstract class CaseMngtBaseImpl
	extends CaseMngtModelImpl implements CaseMngt {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a case mngt model instance should use the <code>CaseMngt</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CaseMngtLocalServiceUtil.addCaseMngt(this);
		}
		else {
			CaseMngtLocalServiceUtil.updateCaseMngt(this);
		}
	}

}