/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package AddAmbulanceDb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Driver service. Represents a row in the &quot;HSP_Driver&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>AddAmbulanceDb.model.impl.DriverModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>AddAmbulanceDb.model.impl.DriverImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Driver
 * @generated
 */
@ProviderType
public interface DriverModel extends BaseModel<Driver> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a driver model instance should use the {@link Driver} interface instead.
	 */

	/**
	 * Returns the primary key of this driver.
	 *
	 * @return the primary key of this driver
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this driver.
	 *
	 * @param primaryKey the primary key of this driver
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this driver.
	 *
	 * @return the uuid of this driver
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this driver.
	 *
	 * @param uuid the uuid of this driver
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the driver ID of this driver.
	 *
	 * @return the driver ID of this driver
	 */
	public long getDriverId();

	/**
	 * Sets the driver ID of this driver.
	 *
	 * @param driverId the driver ID of this driver
	 */
	public void setDriverId(long driverId);

	/**
	 * Returns the hospital ID of this driver.
	 *
	 * @return the hospital ID of this driver
	 */
	public long getHospitalId();

	/**
	 * Sets the hospital ID of this driver.
	 *
	 * @param hospitalId the hospital ID of this driver
	 */
	public void setHospitalId(long hospitalId);

	/**
	 * Returns the ambulance ID of this driver.
	 *
	 * @return the ambulance ID of this driver
	 */
	public long getAmbulanceId();

	/**
	 * Sets the ambulance ID of this driver.
	 *
	 * @param ambulanceId the ambulance ID of this driver
	 */
	public void setAmbulanceId(long ambulanceId);

	/**
	 * Returns the user ID of this driver.
	 *
	 * @return the user ID of this driver
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this driver.
	 *
	 * @param userId the user ID of this driver
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this driver.
	 *
	 * @return the user uuid of this driver
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this driver.
	 *
	 * @param userUuid the user uuid of this driver
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the driver name of this driver.
	 *
	 * @return the driver name of this driver
	 */
	@AutoEscape
	public String getDriverName();

	/**
	 * Sets the driver name of this driver.
	 *
	 * @param driverName the driver name of this driver
	 */
	public void setDriverName(String driverName);

	/**
	 * Returns the contact number of this driver.
	 *
	 * @return the contact number of this driver
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this driver.
	 *
	 * @param contactNumber the contact number of this driver
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the email of this driver.
	 *
	 * @return the email of this driver
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this driver.
	 *
	 * @param email the email of this driver
	 */
	public void setEmail(String email);

	/**
	 * Returns the address of this driver.
	 *
	 * @return the address of this driver
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this driver.
	 *
	 * @param address the address of this driver
	 */
	public void setAddress(String address);

	/**
	 * Returns the status of this driver.
	 *
	 * @return the status of this driver
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this driver.
	 *
	 * @param status the status of this driver
	 */
	public void setStatus(String status);

	/**
	 * Returns the create date of this driver.
	 *
	 * @return the create date of this driver
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this driver.
	 *
	 * @param createDate the create date of this driver
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this driver.
	 *
	 * @return the modified date of this driver
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this driver.
	 *
	 * @param modifiedDate the modified date of this driver
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public Driver cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}