/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package AddAmbulanceDb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Hospital service. Represents a row in the &quot;HSP_Hospital&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>AddAmbulanceDb.model.impl.HospitalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>AddAmbulanceDb.model.impl.HospitalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Hospital
 * @generated
 */
@ProviderType
public interface HospitalModel
	extends BaseModel<Hospital>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hospital model instance should use the {@link Hospital} interface instead.
	 */

	/**
	 * Returns the primary key of this hospital.
	 *
	 * @return the primary key of this hospital
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hospital.
	 *
	 * @param primaryKey the primary key of this hospital
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this hospital.
	 *
	 * @return the uuid of this hospital
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this hospital.
	 *
	 * @param uuid the uuid of this hospital
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the hospital ID of this hospital.
	 *
	 * @return the hospital ID of this hospital
	 */
	public long getHospitalId();

	/**
	 * Sets the hospital ID of this hospital.
	 *
	 * @param hospitalId the hospital ID of this hospital
	 */
	public void setHospitalId(long hospitalId);

	/**
	 * Returns the group ID of this hospital.
	 *
	 * @return the group ID of this hospital
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this hospital.
	 *
	 * @param groupId the group ID of this hospital
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this hospital.
	 *
	 * @return the company ID of this hospital
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this hospital.
	 *
	 * @param companyId the company ID of this hospital
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this hospital.
	 *
	 * @return the user ID of this hospital
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this hospital.
	 *
	 * @param userId the user ID of this hospital
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this hospital.
	 *
	 * @return the user uuid of this hospital
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this hospital.
	 *
	 * @param userUuid the user uuid of this hospital
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this hospital.
	 *
	 * @return the user name of this hospital
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this hospital.
	 *
	 * @param userName the user name of this hospital
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this hospital.
	 *
	 * @return the create date of this hospital
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this hospital.
	 *
	 * @param createDate the create date of this hospital
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this hospital.
	 *
	 * @return the modified date of this hospital
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hospital.
	 *
	 * @param modifiedDate the modified date of this hospital
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the hospital name of this hospital.
	 *
	 * @return the hospital name of this hospital
	 */
	@AutoEscape
	public String getHospitalName();

	/**
	 * Sets the hospital name of this hospital.
	 *
	 * @param hospitalName the hospital name of this hospital
	 */
	public void setHospitalName(String hospitalName);

	/**
	 * Returns the location of this hospital.
	 *
	 * @return the location of this hospital
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this hospital.
	 *
	 * @param location the location of this hospital
	 */
	public void setLocation(String location);

	/**
	 * Returns the address of this hospital.
	 *
	 * @return the address of this hospital
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this hospital.
	 *
	 * @param address the address of this hospital
	 */
	public void setAddress(String address);

	/**
	 * Returns the contact number of this hospital.
	 *
	 * @return the contact number of this hospital
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this hospital.
	 *
	 * @param contactNumber the contact number of this hospital
	 */
	public void setContactNumber(String contactNumber);

	@Override
	public Hospital cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}