/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package checkIndb3.model.impl;

import checkIndb3.model.check;

import checkIndb3.service.checkLocalServiceUtil;

/**
 * The extended model base implementation for the check service. Represents a row in the &quot;practice_check&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link checkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see checkImpl
 * @see check
 * @generated
 */
public abstract class checkBaseImpl extends checkModelImpl implements check {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a check model instance should use the <code>check</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			checkLocalServiceUtil.addcheck(this);
		}
		else {
			checkLocalServiceUtil.updatecheck(this);
		}
	}

}